apiVersion: v1
kind: ServiceAccount
metadata:
  name: iamserviceaccount



---
apiVersion: v1
kind: Pod
metadata:
  name: testirsa
spec:
  serviceAccountName: iamserviceaccount
  containers:
  - image: amazon/aws-cli
    name: testirsa
    command: [ 'sleep' , '3600' ]
    resources: {}


    
